TECH_SKILLS = {
    "python",
    "java",
    "javascript",
    "typescript",
    "react",
    "node.js",
    "fastapi",
    "django",
    "flask",
    "sql",
    "postgresql",
    "mysql",
    "mongodb",
    "docker",
    "kubernetes",
    "aws",
    "azure",
    "gcp",
    "git",
    "linux",
    "redis",
    "rest",
    "graphql",
    "pandas",
    "numpy",
    "scikit-learn",
    "tensorflow",
    "pytorch",
    "machine learning",
    "nlp",
    "ci/cd",
    "terraform",
    "tailwind",
    "html",
    "css",
}

EDUCATION_KEYWORDS = {"bachelor", "master", "phd", "university", "college", "degree"}
EXPERIENCE_KEYWORDS = {"experience", "years", "engineer", "developer", "intern", "lead"}
